# Generated by Django 5.1.1 on 2024-09-19 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=100)),
                (
                    "cambio",
                    models.CharField(
                        choices=[("Automático", "Automático"), ("Manual", "Manual")],
                        max_length=100,
                    ),
                ),
                (
                    "combustivel",
                    models.CharField(
                        choices=[
                            ("Flex", "Flex"),
                            ("Gasolina", "Gasolina"),
                            ("Gasolina e Gás", "Gasolina e Gás"),
                            ("Flex e Gás", "Flex e Gás"),
                            ("Elétrico", "Elétrico"),
                            ("Híbrido", "Híbrido"),
                        ],
                        max_length=100,
                    ),
                ),
                ("quilometragem", models.IntegerField()),
                ("preco", models.FloatField()),
                ("ano_fabrica", models.IntegerField()),
                ("ano_lancamento", models.IntegerField()),
                ("foto_carro", models.ImageField(upload_to="cars/")),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modelo_carro",
                        to="cars.marca",
                    ),
                ),
            ],
        ),
    ]
