# Generated by Django 5.1.1 on 2024-09-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="motor",
            field=models.IntegerField(default=1.0),
        ),
    ]
