# Generated by Django 5.1.1 on 2024-09-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_car_motor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="motor",
            field=models.FloatField(default=1.0, max_length=2),
        ),
    ]
